name: Create Empty Branch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Initialize Blind Repository & Push
        run: |
          mkdir fresh-assets
          cd fresh-assets
          git init
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b assets
          
          echo "This branch is dedicated to assets only." > README.md
          git add README.md
          git commit -m "chore: wipe out history and initialize pure independent assets branch"
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push origin assets --force
